# Generated by Django 4.2.1 on 2024-04-27 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0003_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='user_profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='encyclopedia.userprofile'),
            preserve_default=False,
        ),
    ]
