# Generated by Django 4.2.1 on 2024-04-29 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0004_entry_user_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
