# Generated by Django 4.2.1 on 2024-05-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0007_entry_category_entry_image_entry_reference_entry_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wiki/images/'),
        ),
    ]
