# Generated by Django 4.2.1 on 2024-05-27 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0017_entry_short_description_infobox'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='infobox',
            name='entry',
        ),
        migrations.DeleteModel(
            name='Reference',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='short_description',
        ),
        migrations.DeleteModel(
            name='Infobox',
        ),
    ]
