# Generated by Django 4.2.1 on 2024-06-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0018_delete_category_remove_infobox_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='bio_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
