# Generated by Django 4.2.1 on 2024-07-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0024_tag_remove_entry_tag_entry_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
