# Generated by Django 4.2.1 on 2024-07-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0026_entry_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='visit_count',
            field=models.IntegerField(default=0),
        ),
    ]
