# Generated by Django 4.2.1 on 2024-07-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0027_entry_visit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
